services:
  postgres:
    image: postgres:17
    ports:
      - "54329:5432"
    environment:
      POSTGRES_USER: aimani_ai
      POSTGRES_PASSWORD: aimani_ai
      POSTGRES_DB: aimani_ai
    volumes:
      - aimani_ai-postgres-data:/var/lib/postgresql/data

volumes:
  aimani_ai-postgres-data:
