/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as OrganizationIdHandoffsRouteImport } from './routes/$organizationId/handoffs'
import { Route as OrganizationIdPeopleRouteImport } from './routes/$organizationId/people'
import { Route as OrganizationIdTodosRouteImport } from './routes/$organizationId/todos'
import { Route as OrganizationIdPeopleIndexRouteImport } from './routes/$organizationId/people/index'
import { Route as OrganizationIdPeopleContextMembershipIdTodosRouteImport } from './routes/$organizationId/people/$contextMembershipId/todos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIdHandoffsRoute = OrganizationIdHandoffsRouteImport.update({
  id: '/$organizationId/handoffs',
  path: '/$organizationId/handoffs',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIdPeopleRoute = OrganizationIdPeopleRouteImport.update({
  id: '/$organizationId/people',
  path: '/$organizationId/people',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIdTodosRoute = OrganizationIdTodosRouteImport.update({
  id: '/$organizationId/todos',
  path: '/$organizationId/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIdPeopleIndexRoute =
  OrganizationIdPeopleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganizationIdPeopleRoute,
  } as any)
const OrganizationIdPeopleContextMembershipIdTodosRoute =
  OrganizationIdPeopleContextMembershipIdTodosRouteImport.update({
    id: '/$contextMembershipId/todos',
    path: '/$contextMembershipId/todos',
    getParentRoute: () => OrganizationIdPeopleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/$organizationId/handoffs': typeof OrganizationIdHandoffsRoute
  '/$organizationId/people': typeof OrganizationIdPeopleRouteWithChildren
  '/$organizationId/todos': typeof OrganizationIdTodosRoute
  '/$organizationId/people/': typeof OrganizationIdPeopleIndexRoute
  '/$organizationId/people/$contextMembershipId/todos': typeof OrganizationIdPeopleContextMembershipIdTodosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/$organizationId/handoffs': typeof OrganizationIdHandoffsRoute
  '/$organizationId/todos': typeof OrganizationIdTodosRoute
  '/$organizationId/people': typeof OrganizationIdPeopleIndexRoute
  '/$organizationId/people/$contextMembershipId/todos': typeof OrganizationIdPeopleContextMembershipIdTodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/$organizationId/handoffs': typeof OrganizationIdHandoffsRoute
  '/$organizationId/people': typeof OrganizationIdPeopleRouteWithChildren
  '/$organizationId/todos': typeof OrganizationIdTodosRoute
  '/$organizationId/people/': typeof OrganizationIdPeopleIndexRoute
  '/$organizationId/people/$contextMembershipId/todos': typeof OrganizationIdPeopleContextMembershipIdTodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/organizations'
    | '/$organizationId/handoffs'
    | '/$organizationId/people'
    | '/$organizationId/todos'
    | '/$organizationId/people/'
    | '/$organizationId/people/$contextMembershipId/todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/organizations'
    | '/$organizationId/handoffs'
    | '/$organizationId/todos'
    | '/$organizationId/people'
    | '/$organizationId/people/$contextMembershipId/todos'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/organizations'
    | '/$organizationId/handoffs'
    | '/$organizationId/people'
    | '/$organizationId/todos'
    | '/$organizationId/people/'
    | '/$organizationId/people/$contextMembershipId/todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OrganizationsRoute: typeof OrganizationsRoute
  OrganizationIdHandoffsRoute: typeof OrganizationIdHandoffsRoute
  OrganizationIdPeopleRoute: typeof OrganizationIdPeopleRouteWithChildren
  OrganizationIdTodosRoute: typeof OrganizationIdTodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organizationId/handoffs': {
      id: '/$organizationId/handoffs'
      path: '/$organizationId/handoffs'
      fullPath: '/$organizationId/handoffs'
      preLoaderRoute: typeof OrganizationIdHandoffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organizationId/people': {
      id: '/$organizationId/people'
      path: '/$organizationId/people'
      fullPath: '/$organizationId/people'
      preLoaderRoute: typeof OrganizationIdPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organizationId/todos': {
      id: '/$organizationId/todos'
      path: '/$organizationId/todos'
      fullPath: '/$organizationId/todos'
      preLoaderRoute: typeof OrganizationIdTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organizationId/people/': {
      id: '/$organizationId/people/'
      path: '/'
      fullPath: '/$organizationId/people/'
      preLoaderRoute: typeof OrganizationIdPeopleIndexRouteImport
      parentRoute: typeof OrganizationIdPeopleRoute
    }
    '/$organizationId/people/$contextMembershipId/todos': {
      id: '/$organizationId/people/$contextMembershipId/todos'
      path: '/$contextMembershipId/todos'
      fullPath: '/$organizationId/people/$contextMembershipId/todos'
      preLoaderRoute: typeof OrganizationIdPeopleContextMembershipIdTodosRouteImport
      parentRoute: typeof OrganizationIdPeopleRoute
    }
  }
}

interface OrganizationIdPeopleRouteChildren {
  OrganizationIdPeopleIndexRoute: typeof OrganizationIdPeopleIndexRoute
  OrganizationIdPeopleContextMembershipIdTodosRoute: typeof OrganizationIdPeopleContextMembershipIdTodosRoute
}

const OrganizationIdPeopleRouteChildren: OrganizationIdPeopleRouteChildren = {
  OrganizationIdPeopleIndexRoute: OrganizationIdPeopleIndexRoute,
  OrganizationIdPeopleContextMembershipIdTodosRoute:
    OrganizationIdPeopleContextMembershipIdTodosRoute,
}

const OrganizationIdPeopleRouteWithChildren =
  OrganizationIdPeopleRoute._addFileChildren(OrganizationIdPeopleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OrganizationsRoute: OrganizationsRoute,
  OrganizationIdHandoffsRoute: OrganizationIdHandoffsRoute,
  OrganizationIdPeopleRoute: OrganizationIdPeopleRouteWithChildren,
  OrganizationIdTodosRoute: OrganizationIdTodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
