import { RefreshCw } from 'lucide-react';
import { Link } from '@tanstack/react-router';
import type { TodoHandoffWorkspaceResult } from './handoff-schema';
import { HandoffRequestCard } from './HandoffRequestCard';
import { useState } from 'react';
export function HandoffPage({ organizationId, result, retry }: { organizationId: string; result: TodoHandoffWorkspaceResult; retry?: () => void }) {
 if (result.status !== 'ok') return <section className="content"><div className="empty-surface"><h2>引き継ぎを読み込めませんでした</h2><p>{result.error.message}</p>{retry ? <button className="secondary-button" onClick={retry}><RefreshCw size={16} aria-hidden="true"/>再試行</button> : null}<Link className="secondary-button" to="/organizations">組織を選び直す</Link></div></section>;
 const { workspace } = result; const [liveMessage, setLiveMessage] = useState(''); return <section className="content handoff-page"><div className="handoff-live-region" aria-live="polite" aria-atomic="true">{liveMessage || ' '}</div><header className="people-context"><div><p className="eyebrow">{workspace.organization.name}</p><h2>引き継ぎ</h2><p>担当が変わる仕事を、意図と一緒に確認します。</p></div></header><HandoffSection title="あなたへの依頼" items={workspace.incomingRequests} kind="incoming" onAnnounce={setLiveMessage}/><HandoffSection title="送った依頼" items={workspace.outgoingRequests} kind="outgoing" onAnnounce={setLiveMessage}/><HandoffSection title="最近の引き継ぎ" items={workspace.recentHandoffs} kind="recent" onAnnounce={setLiveMessage}/></section>;
}
function HandoffSection({ title, items, kind, onAnnounce }: { title: string; items: import('@amidala/contracts').TodoHandoffSummary[]; kind: 'incoming'|'outgoing'|'recent'; onAnnounce: (message: string) => void }) { return <section className="handoff-section"><div className="section-heading"><h3>{title}</h3></div>{items.length ? <div className="handoff-list">{items.map((item) => <HandoffRequestCard key={item.handoffId} handoff={item} kind={kind} onAnnounce={onAnnounce}/>)}</div> : <div className="empty-surface"><p>該当する引き継ぎはありません。</p></div>}</section>; }
